version: 2.1
workflows:
  build:
    jobs:
      - build:
          context:
            - dockerhub
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: cimg/base:current
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          name: Init git submodule && clone build-helper
          command: |
            git submodule update --init --recursive
            git clone https://bitbucket.org/code-orange/build-helper-scripts
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: build process
          command: |      
            docker build -t jcivitell/$CIRCLE_PROJECT_REPONAME:latest .
      - run:
          name: upload image
          command: |
            chmod +x build-helper-scripts/semantic-versioning-now.sh
            IMAGEVERSION=$(build-helper-scripts/semantic-versioning-now.sh)
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker image tag jcivitell/$CIRCLE_PROJECT_REPONAME:latest jcivitell/$CIRCLE_PROJECT_REPONAME:$IMAGEVERSION
            docker push -a jcivitell/$CIRCLE_PROJECT_REPONAME
